### ISSUE TITLE
Bayesian online changepoint detection for multivariate data

### ISSUE THREAD

**Issue by sokolov-alex** [hildensia/bayesian_changepoint_detection#11]
Is it possible to make Ryan Adams algorithm to work on multivariate data too?

**Comment by hildensia** [comment]
As far as I can see, the change should be relatively easy, but a bit time consuming. It's only updating the student t distribution to handle multivariate data correctly. It is not yet in scipy, though, AFAIK, so it would need a bit of time to get it in there.

Would you feel confident enough to translate e.g. the wiki article on multivariate student t distributions to a `scipy.stats.multivariate_t`?

**Comment by sokolov-alex** [comment]
I have found a multivariate student t distribution implementation, but I didn't yet find out how to change the update_theta function to handle multivariate data.

**Comment by mathDR** [comment]
You would want to mimic numpy.random.multivariate_normal as that is the main call from scipy.stats.multivariate_normal (the rest is type and size checking).  If we just want a local version, that should be fine.

**Comment by luhgit** [comment]
Hi @sokolov-alex : Did you find a way to update the theta function?

**Comment by vickyf** [comment]
Depending on your goal it might be good enough to implement a multivariate T, which assumes the input variables to be independent. Though this will not capture a change in covariance structure, it might still be useful depending on what you are looking for. On top of that the implementation of this is rather simple.

**Comment by Sandy4321** [comment]
Hello friends, as I can see: Modeling Changing Dependency Structure in
Multivariate Time Series
So you already added this functionality to detect a change in multivariate time series? 
it would great to have it.
Let's say I have 9 time series and small change happen in which of them. This change is not enough to detect by analyzing each one individually, but some aggregation may help?  
Or 5 of them changed and 4 not, so still change will be detected with some probability ?

**Comment by hushchyn-mikhail** [comment]
Hi all!
Are there any changes?

**Comment by Sandy4321** [comment]
Good question

**Comment by TMiguelT** [comment]
I note that, as of this month, scipy now includes an implementation of the PDF for the multivariate t-distribution: https://docs.scipy.org/doc/scipy/reference/release.1.6.0.html#scipy-stats-improvements.

Does that make this easy to implement?

**Comment by TMiguelT** [comment]
I've also found an R implementation of this algorithm that works on multivariate data, which I think could be used as a meaningful reference. In particular, their "update theta" function is here: https://github.com/cran/ocp/blob/890dc2e075d5f310f1ace662bf7e25520d88a2c5/R/gaussian.R#L82-L112

**Comment by hildensia** [comment]
Their code is GPL while this is MIT licence. Make sure you do not port!

Generally, I don't have time to look at this right now, but I'm happy to merge PRs.

**Comment by hildensia** [comment]
We're doing some low level optimizations, so it might be hard to transfer those to the multivariate case, especially using a lib version (we basically implemented the distribution manually), but if you're interested go for it.

**Comment by TMiguelT** [comment]
I reckon I can give this a shot. Is it okay to reference a book or paper for the maths without breaking the MIT license?

**Comment by hildensia** [comment]
Papers and math are totally fine.

**Comment by TMiguelT** [comment]
Draft PR in #26. Happy if anyone with a better grasp of the stats runs an eye over my code.

**Comment by TMiguelT** [comment]
Can we now close this issue as #26 has been merged?
