### ISSUE TITLE
Why the probability exceeds one?

### ISSUE THREAD

**Issue by mike-ocean** [hildensia/bayesian_changepoint_detection#17]
I ran the given online detection example in the [notebook,](https://nbviewer.jupyter.org/github/hildensia/bayesian_changepoint_detection/blob/master/Example%20Code.ipynb) and I assumed the y axis indicating the probability of changepoint (am I right?). But the y value ranged from zero to hundreds. 
I am not very familiar with the math, so can anyone please explain this outcome? 

Thanks.

**Comment by hildensia** [comment]
The third plot in the online example is the probability. The second plot is at each timestep a distribution over the length of the current part.

**Comment by mike-ocean** [comment]
> The third plot in the online example is the probability. The second plot is at each timestep a distribution over the length of the current part.

Thanks you Johannes! I realized this yesterday and just close the issue. But thanks anyway!
