### ISSUE TITLE
Scipy Import Error on newer versions 

### ISSUE THREAD

**Issue by fhaselbeck** [hildensia/bayesian_changepoint_detection#29]
Hi guys,

there is an import issue if one uses newer scipy versions.

Would be a quick fix if you adapt the import statement at `offline_changepoint_detection.py`

```
try:  # SciPy >= 0.19
    from scipy.special import comb, logsumexp
except ImportError:
    from scipy.misc import comb, logsumexp  # noqa
```

**Comment by hildensia** [comment]
Would you mind sending a pull request?

**Comment by fhaselbeck** [comment]
I ust recognized that I installed an old version using pip. 
Error was already fixed: https://github.com/hildensia/bayesian_changepoint_detection/pull/22 

Sorry for the misunderstanding
