### ISSUE TITLE
New release in PyPi?

### ISSUE THREAD

**Issue by lisabutti** [hildensia/bayesian_changepoint_detection#32]
Is it possible to get a new release in PyPi? since the offline detection does not work in the release currently in PyPi.

Thank you

**Comment by MakGulati** [comment]
@lisabutti  are you getting some scipy import problems?

**Comment by lisabutti** [comment]
@MakGulati yes when I try to import the offline_changepoint_detection

**Comment by MakGulati** [comment]
basically scipy developers modified the modules for imports.  For instance `logsumexp` is now in `scipy.special`. I can create a pull request with my changes if it makes sense.
@hildensia @lisabutti

**Comment by sayanchk** [comment]
Is there any progress in this issue? Can we make a new release to support the latest scipy versions?

We have dependency on this package and blocked to support the latest scipy releases.

**Comment by hildensia** [comment]
If somebody does a pill request I'm happy to merge it

**Comment by MakGulati** [comment]
@sayanchk @hildensia @lisabutti 
Recent commit (one month ago) by David Nicholson addresses this scipy import issue. If you try updated example notebooks, it should work just fine.

**Comment by sayanchk** [comment]
@hildensia @MakGulati This package is part of our dependency and we install it on the fly whenever we pip install our package. Therefore, we need it pypi.

 I am not seeing any instruction for the CI/CD. Can you please share how to make the latest version (0.3) available in pypi? I can then make the necessary changes.

**Comment by shahsmit14** [comment]
I have created a PR to help resolve this issue and requires creating a token which is defined in the description.  
https://github.com/hildensia/bayesian_changepoint_detection/pull/35

**Comment by shahsmit14** [comment]
Can I get some eyes on the PR? cc: @hildensia

**Comment by hildensia** [comment]
Fixed by #35
