### ISSUE TITLE
Example notebook does not work

### ISSUE THREAD

**Issue by chryss** [hildensia/bayesian_changepoint_detection#37]
If I click on the "example notebook" work - an nbviewer link - I get a "too many redirects" error. 

It would be nice if the example notebook was easily accessible in the repo (maybe I overlooked it... ) because we don't need a live notebook / nbviewer to figure out whether the example fits our use case.

**Comment by hildensia** [comment]
I you simply open the notebook source on github, the github interface renders the notebook.

**Comment by hildensia** [comment]
fixed the link in #[6975c16](https://github.com/hildensia/bayesian_changepoint_detection/commit/6975c16c860f70ff7bd707aec3109b81056faf6a)
