### ISSUE TITLE
Add pyx file again

### ISSUE THREAD

**Issue by hildensia** [hildensia/bayesian_changepoint_detection#6]
Was removed during a PR. Is there a good way to keep cython and python in sync. I'm not sure if I prefer one over the other (python is better for debugging, cython is faster).

**Comment by mathDR** [comment]
I haven't found a good way to keep them in sync.  I think right now the examples are plenty fast.  In any case, I added the original cy_offline.pyx and cy_offline_changepoint_detection.py files back to the repository.

**Comment by mathDR** [comment]
Also, its not clear that the speedup gains are optimized.  If the new multivariate likelihoods are to by cythonized, then outer(), slogdet(), multigammaln() and gammaln() should all be cythonized. Thoughts?

**Comment by hildensia** [comment]
It is probably not really worthwhile using cython right now. I just tried it for an experiment, but it wasn't really speeding things up a lot. For my part it can be removed.

**Comment by mathDR** [comment]
Should we close this issue then?

**Comment by hildensia** [comment]
Yepp. You're right.
